# Generated by Django 3.1.2 on 2020-10-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogovor_query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='table_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер стола'),
        ),
    ]
